server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/**

html:
  path: C:\\Users\\Administrator\\IdeaProjects\\j38-springboot\\springboot-02\\src\\main\\resources\\templates\\